### ISSUE TITLE
Can't force and trigger single Task in TYPO3 6.2.31

### ISSUE THREAD

**Issue by mogensf** [WebentwicklerAt/typo3-scheduler_http#4]
When triggering and forcing a single task in typo3 6.2.31 all tasks are triggered but not forced.

I think this happens because the taskid is appearing directly after the -i param in the execcution Command.
Adding a space between -i and $taskId in Ext:scheduler_http\Classes\Eid\SchedulerHttpEid.php Line 195 everything works fine.
Only tested on my local Ubuntu 16.04. Server. Maybe it works better on other OS.

**Comment by leitgab** [comment]
Thank you for your feedback! I commited an updated version and uploaded it to TER.
