### ISSUE TITLE
Call  a Controller/Action by  scheduler

### ISSUE THREAD

**Issue by frikas** [WebentwicklerAt/typo3-scheduler_http#9]
Hi, I would like to call a Controller / Action via the scheduler. I have not found any hints in the task list.  How could I accomplish this? The Goal is only to trigger the Controller/Action without any parameters.

**Comment by leitgab** [comment]
Therefore you have to use Symfony Console Commands:
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/CommandControllers/Index.html
